// Base route.
GET http://localhost:3000
###

// Get news feed.
GET http://localhost:3000/api/news
###

// Get a news article.
GET http://localhost:3000/api/news/:id
###

// Delete a news article.
GET http://localhost:3000/api/news/delete/:id
###

// Create a new news article.
POST http://localhost:3000/api/news/create
Content-Type: application/json

{
    "title": "",
    "content": "",
    "image_uri": "",
    "date": ""
}
###

// Get event overview.
GET http://localhost:3000/api/events
###

// Get an event.
GET http://localhost:3000/api/events/:id
###

// Create a new event.
POST http://localhost:3000/api/events/create
Content-Type: application/json

{
    "title": "",
    "description": "",
    "location": "",
    "start_time": "",
    "image_uri": "",
    "is_public": true
}
###

// Alter attendance response for event.
POST http://localhost:3000/api/events/attendance
Content-Type: application/json

{
    "event_id": "",
    "attendance": "",
    "old_attendance": ""
}
###

// Delete an event.
GET http://localhost:3000/api/events/delete/:id
###

// Get the chat overview.
GET http://localhost:3000/api/chat
###

// Get a thread.
GET http://localhost:3000/api/chat/:id
###